-- 045: Quote system, booking numbers, extended job lifecycle, company
-- document verification, configurable verification requirements, notification
-- categories (production correction pass).
--
--  1) Real Quote entity (spec: "A QUOTE IS NOT A COMPLETED JOB"). Quotes carry
--     the granular lifecycle (DRAFT/SENT/VIEWED/ACCEPTED/DECLINED/EXPIRED/
--     CANCELLED) with itemized charges, duration, notes, attachments, expiry.
--  2) Permanent human-readable booking numbers (PF-YYYY-NNNNNN) generated by
--     the database itself via BEFORE INSERT trigger - never the frontend.
--  3) Extended job status set: quote_requested, booking_confirmed,
--     customer_confirmed_completion, payment_*, closed, disputed,
--     refund_requested, refunded.
--  4) verification_documents generalized: companies can own documents,
--     statuses gain under_review/verified/expired, reviewer + reason + expiry
--     + OCR extraction metadata.
--  5) verification_requirements: configurable per-country document rules.
--  6) notifications gain category + severity for the admin notification center.
--  7) company_profiles gain verification workflow fields + profile image.

-- ─────────────────────────────────────────────────────────── 1) QUOTES ──
create table if not exists quotes (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references jobs(id) on delete cascade,
  customer_id uuid not null references users(id) on delete cascade,
  company_id uuid references company_profiles(id) on delete set null,
  fundi_id uuid references fundis(user_id) on delete set null,
  service_category text,
  description text,
  amount numeric(12, 2) not null check (amount > 0),
  currency text not null default 'KES',
  labor_amount numeric(12, 2) check (labor_amount is null or labor_amount >= 0),
  materials_amount numeric(12, 2) check (materials_amount is null or materials_amount >= 0),
  additional_charges jsonb not null default '[]'::jsonb,
  estimated_duration_hours numeric(6, 1),
  notes text,
  attachments jsonb not null default '[]'::jsonb,
  expires_at timestamptz,
  status text not null default 'sent'
    check (status in ('draft', 'sent', 'viewed', 'accepted', 'declined', 'expired', 'cancelled')),
  viewed_at timestamptz,
  decided_at timestamptz,
  decision_note text,
  question_thread jsonb not null default '[]'::jsonb,
  created_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_quotes_job on quotes(job_id);
create index if not exists idx_quotes_customer on quotes(customer_id);
create index if not exists idx_quotes_company on quotes(company_id) where company_id is not null;
create index if not exists idx_quotes_fundi on quotes(fundi_id) where fundi_id is not null;
create index if not exists idx_quotes_status on quotes(status);
-- A job may only have ONE live quote at a time (draft/sent/viewed).
create unique index if not exists idx_quotes_one_live_per_job
  on quotes(job_id) where status in ('draft', 'sent', 'viewed');

-- ────────────────────────────────────────────── 2) BOOKING NUMBERS ──
alter table jobs add column if not exists booking_number text;
create unique index if not exists idx_jobs_booking_number
  on jobs(booking_number) where booking_number is not null;

create sequence if not exists booking_number_seq start 1;

create or replace function patafundi_set_booking_number() returns trigger as $$
begin
  if new.booking_number is null or new.booking_number = '' then
    new.booking_number := 'PF-' || to_char(coalesce(new.created_at, now()), 'YYYY')
      || '-' || lpad(nextval('booking_number_seq')::text, 6, '0');
  end if;
  return new;
end;
$$ language plpgsql;

drop trigger if exists trg_jobs_booking_number on jobs;
create trigger trg_jobs_booking_number
  before insert on jobs
  for each row execute function patafundi_set_booking_number();

-- Backfill existing jobs (each gets its own sequence draw - collision-safe).
update jobs
  set booking_number = 'PF-' || to_char(coalesce(created_at, now()), 'YYYY')
    || '-' || lpad(nextval('booking_number_seq')::text, 6, '0')
  where booking_number is null;

-- ─────────────────────────────────────────── 3) JOB STATUS EXTENSION ──
-- Full lifecycle (spec): REQUESTED → MATCHING → QUOTE_REQUESTED → QUOTE_SENT
-- (offered) → [quote accepted] BOOKING_CONFIRMED → SCHEDULED → ARRIVING →
-- CHECKED_IN → IN_PROGRESS → COMPLETION_PENDING → CUSTOMER_CONFIRMED_COMPLETION
-- → PAYMENT_* → COMPLETED → CLOSED, plus alternative states.
alter table jobs drop constraint if exists jobs_status_check;
alter table jobs add constraint jobs_status_check check (status in (
  'pending', 'matching', 'quote_requested', 'offered', 'accepted',
  'booking_confirmed', 'assigned', 'scheduled',
  'on_the_way', 'arrived', 'in_progress', 'completion_requested',
  'customer_confirmed_completion',
  'payment_pending', 'payment_processing', 'payment_confirmed',
  'completed', 'closed',
  'cancelled', 'failed', 'expired',
  'disputed', 'refund_requested', 'refunded'
));

-- Reaper/expiry indexes still valid; add scan coverage for quote states.
create index if not exists idx_jobs_quote_scan
  on jobs(updated_at) where status in ('pending', 'matching', 'quote_requested', 'offered');

-- ─────────────────────────────── 4) VERIFICATION DOCUMENTS GENERALIZED ──
-- Companies need documents too. Keep legacy fundi rows working: fundi_id
-- becomes nullable and owner_type disambiguates.
alter table verification_documents alter column fundi_id drop not null;
alter table verification_documents add column if not exists owner_type text not null default 'fundi';
alter table verification_documents add column if not exists company_id uuid references company_profiles(id) on delete cascade;

-- Broaden document types (company registration set + legacy fundi set).
alter table verification_documents drop constraint if exists verification_documents_document_type_check;
alter table verification_documents add constraint verification_documents_document_type_check
  check (document_type in (
    'id_front', 'id_back', 'selfie_id', 'certificate', 'business_permit',
    'company_registration', 'owner_id', 'tax_registration',
    'address_evidence', 'professional_license', 'insurance', 'other'
  ));

-- Canonical statuses: pending → under_review → verified/rejected → expired.
-- Legacy 'approved' is kept readable for old rows; new writes use 'verified'.
alter table verification_documents drop constraint if exists verification_documents_status_check;
alter table verification_documents add constraint verification_documents_status_check
  check (status in ('pending', 'under_review', 'verified', 'approved', 'rejected', 'reupload_requested', 'expired'));
update verification_documents set status = 'verified' where status = 'approved';

alter table verification_documents
  add column if not exists reviewer_user_id uuid references users(id) on delete set null,
  add column if not exists reviewed_at timestamptz,
  add column if not exists rejection_reason text,
  add column if not exists expires_at timestamptz,
  add column if not exists extracted_data jsonb not null default '{}'::jsonb,
  add column if not exists verification_metadata jsonb not null default '{}'::jsonb;

create index if not exists idx_verification_documents_company on verification_documents(company_id) where company_id is not null;
create index if not exists idx_verification_documents_status on verification_documents(status);

-- ───────────────────────────── 5) CONFIGURABLE VERIFICATION RULES ──
create table if not exists verification_requirements (
  id uuid primary key default gen_random_uuid(),
  subject_type text not null check (subject_type in ('fundi', 'company')),
  country_code text not null default '*',
  document_type text not null,
  is_required boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (subject_type, country_code, document_type)
);

-- Sensible global defaults (per-country rows override when present).
insert into verification_requirements (subject_type, country_code, document_type, is_required)
values
  ('fundi', '*', 'id_front', true),
  ('fundi', '*', 'id_back', true),
  ('fundi', '*', 'selfie_id', true),
  ('company', '*', 'company_registration', true),
  ('company', '*', 'owner_id', true),
  ('company', '*', 'tax_registration', false),
  ('company', '*', 'address_evidence', false),
  ('company', '*', 'professional_license', false),
  ('company', '*', 'insurance', false)
on conflict (subject_type, country_code, document_type) do nothing;

-- ─────────────────────────────────────── 6) NOTIFICATION CATEGORIES ──
alter table notifications add column if not exists category text;
alter table notifications drop constraint if exists notifications_severity_check;
alter table notifications add column if not exists severity text not null default 'normal';
alter table notifications add constraint notifications_severity_check
  check (severity in ('critical', 'high', 'normal', 'low'));

update notifications set category = case
  when type ilike '%error%' or type ilike '%system%' then 'system'
  when type ilike '%fraud%' or type ilike '%security%' or type ilike '%login%' or type ilike '%device%' then 'security'
  when type ilike '%verif%' or type ilike '%document%' then 'verification'
  when type ilike '%company%' or type ilike '%application%' then 'companies'
  when type ilike '%payout%' or type ilike '%payment%' or type ilike '%refund%' or type ilike '%escrow%' then 'payments'
  when type ilike '%dispute%' then 'disputes'
  when type ilike '%fundi%' then 'fundis'
  when type ilike '%job%' or type ilike '%quote%' then 'customers'
  else 'system'
end
where category is null;

create index if not exists idx_notifications_category on notifications(category) where category is not null;

-- ──────────────────────────────────── 7) COMPANY VERIFICATION FIELDS ──
alter table company_profiles add column if not exists verification_status text not null default 'unverified';
alter table company_profiles drop constraint if exists company_profiles_verification_status_check;
alter table company_profiles add constraint company_profiles_verification_status_check
  check (verification_status in ('unverified', 'pending', 'under_review', 'verified', 'rejected', 'suspended'));
alter table company_profiles add column if not exists profile_image_url text;
alter table company_profiles add column if not exists verification_notes text;
alter table company_profiles add column if not exists verified_at timestamptz;
alter table company_profiles add column if not exists documents_status text not null default 'pending';
alter table company_profiles drop constraint if exists company_profiles_documents_status_check;
alter table company_profiles add constraint company_profiles_documents_status_check
  check (documents_status in ('none', 'pending', 'under_review', 'verified', 'rejected'));

-- Honest backfill: verification was never document-driven before, so every
-- existing company enters the new workflow as under review (NOT auto-verified).
update company_profiles
  set verification_status = case when status = 'suspended' then 'suspended' else 'under_review' end,
      documents_status = 'pending'
  where verification_status = 'unverified';

-- ─────────────────────────────── 8) JOB TIMELINE EVENT TYPES ──
-- The central state machine writes status_<state> events plus quote lifecycle
-- events; extend the CHECK to cover the full canonical lifecycle.
ALTER TABLE job_timeline DROP CONSTRAINT IF EXISTS job_timeline_event_type_check;
ALTER TABLE job_timeline ADD CONSTRAINT job_timeline_event_type_check CHECK (event_type IN (
  'job_created', 'job_posted', 'fundi_matched', 'fundi_accepted', 'fundi_arrived',
  'work_started', 'work_completed', 'customer_confirmed', 'payment_made',
  'escrow_released', 'payout_requested', 'payout_completed', 'job_cancelled',
  'company_accepted', 'quote_sent', 'technician_assigned', 'technician_unassigned',
  'status_changed', 'quote_approved', 'quote_rejected', 'review_submitted',
  'quote_updated', 'quote_accepted', 'quote_declined', 'quote_question',
  'status_pending', 'status_matching', 'status_quote_requested', 'status_offered',
  'status_accepted', 'status_booking_confirmed', 'status_assigned', 'status_scheduled',
  'status_on_the_way', 'status_arrived', 'status_in_progress', 'status_completion_requested',
  'status_customer_confirmed_completion', 'status_payment_pending', 'status_payment_processing',
  'status_payment_confirmed', 'status_completed', 'status_closed', 'status_cancelled',
  'status_failed', 'status_expired', 'status_disputed', 'status_refund_requested',
  'status_refunded'
));

-- ───────────────────────────── 9) COMPANY SUBMISSION TRACKING ──
alter table company_profiles add column if not exists submitted_at timestamptz;

-- ───────────────────────── 10) DOCUMENT REVIEW TIMESTAMPS ──
alter table verification_documents add column if not exists updated_at timestamptz not null default now();
